### ISSUE TITLE
nothing seems to initiate 

### ISSUE THREAD

**Issue by Soldierofthelam** [alp1x/um-soup#2]
not sure if it's a python problem or?
but entering the path and right clicking just shuts python down
![Screenshot 2023-04-26 153321](https://user-images.githubusercontent.com/117047687/234687738-9636ff50-b901-4fd8-96af-29b3c5791fab.png)
![Screenshot 2023-04-26 154256](https://user-images.githubusercontent.com/117047687/234687760-b641224b-4c6b-4872-893e-e1a540a0f991.png)

**Comment by alp1x** [comment]
* Uninstall Python and reinstall it, right click and the terminal doesn't close, it just pastes what you copied, and do not install from microsoft store 

* Add python path if not found after installing python
