### ISSUE TITLE
Some EUP clothing unrecognised

### ISSUE THREAD

**Issue by FizzGamingJR** [alp1x/um-soup#3]
Although some items of clothing such as body Armor and vests are recognised on my server, on most occasions shirts, hands, jackets, shoes and pants are not and always show up as "No Results Found" this is both for mp_m and mp_f and also the issue persists in Chill Mode and Aggressive Mode.
Is there any fix to this?

**Comment by alp1x** [comment]
> Although some items of clothing such as body Armor and vests are recognised on my server, on most occasions shirts, hands, jackets, shoes and pants are not and always show up as "No Results Found" this is both for mp_m and mp_f and also the issue persists in Chill Mode and Aggressive Mode. Is there any fix to this?

Does this only happen with EUP clothes and is your EUP clothes in a separate folder?

**Comment by FizzGamingJR** [comment]
> > Although some items of clothing such as body Armor and vests are recognised on my server, on most occasions shirts, hands, jackets, shoes and pants are not and always show up as "No Results Found" this is both for mp_m and mp_f and also the issue persists in Chill Mode and Aggressive Mode. Is there any fix to this?
> 
> Does this only happen with EUP clothes and is your EUP clothes in a separate folder?

Apologise, only just now saw this reply. Cheers for the quick response!
This issue only occurs on EUP clothing, my EUP clothing is all in one stream folder not organised at all, as mentioned in the OP (Originial Post) the tool works absolutely perfect on particular items of clothing such as body armor but as soon as I try to use it on something else such as Overlay/Jackets or Pants it shits itself!

Hopefully I hear back from you soon, and as mentioned previously my sincerest apologies for the late reply, hopefully you are still happy assisting after you have closed this issue!

Bye for now.

**Comment by alp1x** [comment]
> > > Although some items of clothing such as body Armor and vests are recognised on my server, on most occasions shirts, hands, jackets, shoes and pants are not and always show up as "No Results Found" this is both for mp_m and mp_f and also the issue persists in Chill Mode and Aggressive Mode. Is there any fix to this?
> > 
> > 
> > Does this only happen with EUP clothes and is your EUP clothes in a separate folder?
> 
> Apologise, only just now saw this reply. Cheers for the quick response! This issue only occurs on EUP clothing, my EUP clothing is all in one stream folder not organised at all, as mentioned in the OP (Originial Post) the tool works absolutely perfect on particular items of clothing such as body armor but as soon as I try to use it on something else such as Overlay/Jackets or Pants it shits itself!
> 
> Hopefully I hear back from you soon, and as mentioned previously my sincerest apologies for the late reply, hopefully you are still happy assisting after you have closed this issue!
> 
> Bye for now.


Are your EUP outfits in a different folder inside your main streaming file?

**Comment by FizzGamingJR** [comment]
> > > > Although some items of clothing such as body Armor and vests are recognised on my server, on most occasions shirts, hands, jackets, shoes and pants are not and always show up as "No Results Found" this is both for mp_m and mp_f and also the issue persists in Chill Mode and Aggressive Mode. Is there any fix to this?
> 
> > > 
> 
> > > 
> 
> > > Does this only happen with EUP clothes and is your EUP clothes in a separate folder?
> 
> > 
> 
> > Apologise, only just now saw this reply. Cheers for the quick response! This issue only occurs on EUP clothing, my EUP clothing is all in one stream folder not organised at all, as mentioned in the OP (Originial Post) the tool works absolutely perfect on particular items of clothing such as body armor but as soon as I try to use it on something else such as Overlay/Jackets or Pants it shits itself!
> 
> > 
> 
> > Hopefully I hear back from you soon, and as mentioned previously my sincerest apologies for the late reply, hopefully you are still happy assisting after you have closed this issue!
> 
> > 
> 
> > Bye for now.
> 
> 
> 
> 
> 
> Are your EUP outfits in a different folder inside your main streaming file?
> 
> 
> 
> 

They are not in a different folder inside the streaming file!

**Comment by alp1x** [comment]
> try this 
https://github.com/alp1x/um-soup/releases/tag/v1.5.0

**Comment by FizzGamingJR** [comment]
> > try this
> > https://github.com/alp1x/um-soup/releases/tag/v1.5.0

I have just now added this to my server and I can see that it has updated messages upon being given no results dialogue, with that being said it hasn't seemed to have resolved the issue for me.
As I'm writing this I had just tried it on multiple pieces of clothing all of which I know for definite is not default GTA V clothes with no luck, alongside the above I have also just located that the tool doesn't seem to work on some Armor but does on others which is very strange. I have attached an image below in-case I have worded that in a confusing way!

![image](https://user-images.githubusercontent.com/28313136/236636937-a5089bd5-69e8-47f6-878d-3bafeffbea5c.png)

**Comment by alp1x** [comment]
> > > try this
> > > https://github.com/alp1x/um-soup/releases/tag/v1.5.0
> 
> I have just now added this to my server and I can see that it has updated messages upon being given no results dialogue, with that being said it hasn't seemed to have resolved the issue for me. As I'm writing this I had just tried it on multiple pieces of clothing all of which I know for definite is not default GTA V clothes with no luck, alongside the above I have also just located that the tool doesn't seem to work on some Armor but does on others which is very strange. I have attached an image below in-case I have worded that in a confusing way!
> 
> ![image](https://user-images.githubusercontent.com/28313136/236636937-a5089bd5-69e8-47f6-878d-3bafeffbea5c.png)

If your stream file is specified with .meta in fxmanifest.lua, most slot numbers will not match

**Comment by FizzGamingJR** [comment]
> > > > try this
> 
> > > > https://github.com/alp1x/um-soup/releases/tag/v1.5.0
> 
> > 
> 
> > I have just now added this to my server and I can see that it has updated messages upon being given no results dialogue, with that being said it hasn't seemed to have resolved the issue for me. As I'm writing this I had just tried it on multiple pieces of clothing all of which I know for definite is not default GTA V clothes with no luck, alongside the above I have also just located that the tool doesn't seem to work on some Armor but does on others which is very strange. I have attached an image below in-case I have worded that in a confusing way!
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/28313136/236636937-a5089bd5-69e8-47f6-878d-3bafeffbea5c.png)
> 
> 
> 
> If your stream file is specified with .meta in fxmanifest.lua, most slot numbers will not match

Hello there,
No clothing items within my server have a meta, obviously apart from custom addon clothing which is in a separate resource nowhere near the EUP-Stream. Everything in my EUP-Stream folder is either .YTDs or .YDDs and no .Metas whatsoever.
The fxmanifest.lua does not execute any client, server or meta script but instead only contains the manifest version to stream the actual files and nothing more.
